//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace film_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public feedback() { }
        public feedback(string user_login, long film_id, decimal mark, string text)
        {
            this.user_login = user_login;
            this.film_id = film_id;
            this.mark = mark;
            this.text = text;
        }
        public string user_login { get; set; }
        public long film_id { get; set; }
        public decimal mark { get; set; }
        public string text { get; set; }
    
        public virtual film film { get; set; }
        public virtual user user { get; set; }
    }
}
