//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace film_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public film()
        {
            this.feedback = new HashSet<feedback>();
            this.person_film = new HashSet<person_film>();
            this.genre = new HashSet<genre>();
        }
        public film(string name, string description, short duration, long tallage)
        {
            this.name = name;
            this.description = description;
            this.duration = duration;
            this.tallage = tallage;
            this.feedback = new HashSet<feedback>();
            this.person_film = new HashSet<person_film>();
            this.genre = new HashSet<genre>();
        }
        public void Update(string name, string description, short duration, long tallage)
        {
            this.name = name;
            this.description = description;
            this.duration = duration;
            this.tallage = tallage;
        }
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public short duration { get; set; }
        public long tallage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback> feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<person_film> person_film { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genre> genre { get; set; }
    }
}
