//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace film_service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class film_serviceEntities : DbContext
    {
        public film_serviceEntities()
            : base("name=film_serviceEntities")
        {
        }
        public film_serviceEntities(string connectionString)
               : base(connectionString)
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<feedback> feedback { get; set; }
        public virtual DbSet<film> film { get; set; }
        public virtual DbSet<gender> gender { get; set; }
        public virtual DbSet<genre> genre { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<person_film> person_film { get; set; }
        public virtual DbSet<post> post { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
