//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace film_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_film
    {
        public person_film() { }
        public person_film(long film_id, long person_id, int post_id)
        {
            this.film_id = film_id;
            this.person_id = person_id;
            this.post_id = post_id;
        }
        public long id { get; set; }
        public long film_id { get; set; }
        public long person_id { get; set; }
        public int post_id { get; set; }
    
        public virtual film film { get; set; }
        public virtual person person { get; set; }
        public virtual post post { get; set; }
    }
}
