//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace film_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public person()
        {
            this.person_film = new HashSet<person_film>();
        }
        public person(string first_name, string middle_name, string last_name, byte age, short gender_id, byte height)
        {
            this.first_name = first_name;
            this.middle_name = middle_name;
            this.last_name = last_name;
            this.age = age;
            this.gender_id = gender_id;
            this.height = height;
            this.person_film = new HashSet<person_film>();
        }
        public override string ToString()
        {
            return this.first_name + ";" + this.middle_name + ";" + this.last_name + ";" + this.age + ";" + this.height;
        }
        public void Update(string first_name, string middle_name, string last_name, byte age, short gender_id, byte height)
        {
            this.first_name = first_name;
            this.middle_name = middle_name;
            this.last_name = last_name;
            this.age = age;
            this.gender_id = gender_id;
            this.height = height;
        }

        public long id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public byte age { get; set; }
        public short gender_id { get; set; }
        public Nullable<byte> height { get; set; }
    
        public virtual gender gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<person_film> person_film { get; set; }
    }
}
